from __future__ import annotations

from pathlib import Path

import pytest

from reports.console import ConsoleReporter
from scanner.findings import Finding, Severity
from scanner.model import Language

# Default values used to create representative findings for reporter tests.
DEFAULT_RULE_ID: str = "GEN001"
DEFAULT_RULE_NAME: str = "Hardcoded Credentials"
DEFAULT_DESCRIPTION: str = "Example description."
DEFAULT_RECOMMENDATION: str = "Example recommendation."

DEFAULT_LINE_NUMBER: int = 3
DEFAULT_COLUMN_NUMBER: int = 1


# Expected output fragments generated by the console reporter.
REPORT_TITLE: str = "Tree-Sitter Vulnerability Scanner"
NO_VULNERABILITIES_MESSAGE: str = "No vulnerabilities detected."
SUMMARY_SECTION_TITLE: str = "Summary"

FILE_SECTION_PREFIX: str = "File:"


def _create_test_finding(
    source_file_path: Path,
    *,
    rule_id: str = DEFAULT_RULE_ID,
    rule_name: str = DEFAULT_RULE_NAME,
    severity: Severity = Severity.HIGH,
    line_number: int = DEFAULT_LINE_NUMBER,
    column_number: int = DEFAULT_COLUMN_NUMBER,
) -> Finding:
    """
    Create a representative Finding instance for reporter tests.

    The scanner core and reporting layer are separated by the Finding
    model. This helper creates realistic findings without depending on
    scanner execution logic, allowing the reporter behaviour to be tested
    independently.
    """

    return Finding(
        vulnerability_rule_id=rule_id,
        vulnerability_rule_name=rule_name,
        description=DEFAULT_DESCRIPTION,
        recommendation=DEFAULT_RECOMMENDATION,
        severity=severity,
        source_file_path=source_file_path,
        programming_language=Language.PYTHON,
        line_number=line_number,
        column_number=column_number,
    )


def test_report_without_findings(capsys: pytest.CaptureFixture[str]) -> None:
    """
    Verify that an empty report is formatted correctly.

    The reporter must handle the absence of findings gracefully and
    must not display a summary section when there is nothing to report.
    """

    reporter: ConsoleReporter = ConsoleReporter()

    reporter.report([])

    output: str = capsys.readouterr().out

    assert REPORT_TITLE in output
    assert NO_VULNERABILITIES_MESSAGE in output
    assert SUMMARY_SECTION_TITLE not in output


def test_single_finding_is_reported(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """
    Verify that a single finding is printed completely.

    The report must contain all relevant information provided by the
    Finding model.
    """

    source_file_path: Path = tmp_path / "example.py"

    source_file_path.write_text(
        "\n".join(
            [
                "a = 1",
                "b = 2",
                'password = "secret"',
                "print(password)",
                "print('done')",
            ]
        ),
        encoding="utf-8",
    )

    reporter: ConsoleReporter = ConsoleReporter()

    reporter.report(
        [
            _create_test_finding(source_file_path),
        ]
    )

    output: str = capsys.readouterr().out

    assert DEFAULT_RULE_ID in output
    assert DEFAULT_RULE_NAME in output
    assert Severity.HIGH.name in output

    assert DEFAULT_DESCRIPTION in output
    assert DEFAULT_RECOMMENDATION in output

    assert str(source_file_path) in output

    assert f"{DEFAULT_LINE_NUMBER}:{DEFAULT_COLUMN_NUMBER}" in output


def test_code_context_is_printed(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """
    Verify that surrounding source code is printed.

    Showing source context helps users understand the vulnerability
    location and improves the usability of generated reports.
    """

    source_file_path: Path = tmp_path / "example.py"

    source_file_path.write_text(
        "\n".join(
            [
                "line1",
                "line2",
                "line3",
                "line4",
                "line5",
            ]
        ),
        encoding="utf-8",
    )

    reporter: ConsoleReporter = ConsoleReporter()

    reporter.report(
        [
            _create_test_finding(
                source_file_path,
                line_number=3,
            )
        ]
    )

    output: str = capsys.readouterr().out

    for source_line in [
        "line1",
        "line2",
        "line3",
        "line4",
        "line5",
    ]:
        assert source_line in output

    assert ">    3 | line3" in output


def test_multiple_findings_are_grouped_by_file(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """
    Verify that findings belonging to the same file are grouped together.

    The reporter should avoid repeating file information when multiple
    vulnerabilities originate from the same source file.
    """

    source_file_path: Path = tmp_path / "example.py"

    source_file_path.write_text(
        "\n".join(
            [
                "line1",
                "line2",
                "line3",
                "line4",
                "line5",
            ]
        ),
        encoding="utf-8",
    )

    reporter: ConsoleReporter = ConsoleReporter()

    reporter.report(
        [
            _create_test_finding(
                source_file_path,
                rule_id="GEN001",
                line_number=2,
            ),
            _create_test_finding(
                source_file_path,
                rule_id="GEN002",
                rule_name="Unsafe Code Execution",
                severity=Severity.CRITICAL,
                line_number=4,
            ),
        ]
    )

    output: str = capsys.readouterr().out

    assert output.count(FILE_SECTION_PREFIX) == 1

    assert "GEN001" in output
    assert "GEN002" in output


def test_summary_contains_correct_statistics(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """
    Verify that the summary reports correct vulnerability statistics.

    The reporter must aggregate findings by severity level and display
    the total number of detected vulnerabilities.
    """

    source_file_path: Path = tmp_path / "example.py"

    source_file_path.write_text(
        "print('Hello')",
        encoding="utf-8",
    )

    reporter: ConsoleReporter = ConsoleReporter()

    reporter.report(
        [
            _create_test_finding(
                source_file_path,
                severity=Severity.HIGH,
            ),
            _create_test_finding(
                source_file_path,
                rule_id="GEN002",
                severity=Severity.CRITICAL,
            ),
            _create_test_finding(
                source_file_path,
                rule_id="GEN003",
                severity=Severity.HIGH,
            ),
        ]
    )

    output: str = capsys.readouterr().out

    assert SUMMARY_SECTION_TITLE in output

    assert "Total findings : 3" in output

    assert "LOW      : 0" in output
    assert "MEDIUM   : 0" in output
    assert "HIGH     : 2" in output
    assert "CRITICAL : 1" in output


def test_findings_from_multiple_files_are_separated(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """
    Verify that findings from different files are separated.

    Grouping by source file improves readability and allows the report
    to scale when analysing larger projects.
    """

    first_source_file: Path = tmp_path / "first.py"
    second_source_file: Path = tmp_path / "second.py"

    first_source_file.write_text(
        "print(1)",
        encoding="utf-8",
    )

    second_source_file.write_text(
        "print(2)",
        encoding="utf-8",
    )

    reporter: ConsoleReporter = ConsoleReporter()

    reporter.report(
        [
            _create_test_finding(first_source_file),
            _create_test_finding(
                second_source_file,
                rule_id="GEN002",
            ),
        ]
    )

    output: str = capsys.readouterr().out

    assert f"{FILE_SECTION_PREFIX} {first_source_file}" in output
    assert f"{FILE_SECTION_PREFIX} {second_source_file}" in output

    assert output.count(FILE_SECTION_PREFIX) == 2
